---
- hosts: webserver
  become: True
  tasks:
    - name: Install package
      yum:
        name: "httpd"
        state: "present"
    - name: start services
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy war
      copy:
        src: /var/lib/jenkins/workspace/my-app3-project/target/
        dest: /var/www/html
