---
- hosts: webserver
  become: True
  tasks:
    - name: Install package
      yum:
        name: "httpd"
        state: "present"
    - name: start services
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy war
      copy:
        src: */target/my-app-1.0-SNAPSHOT.jar
        dest: /var/www/html
